#!/bin/sh
trap : INT
for dir in config/docs/*/; do
  [ "$(find "$dir" -maxdepth 1 -name '*.md' -print -quit)" != "" ] || continue
  lang=$(basename "$dir")
  ref=""
  [ "$lang" = "en" ] || ref=" ($lang)"
  echo "Binding $lang book... [ctrl+c to skip]"
  metadata_file="${TMPDIR:-/tmp}/epub-tags-$lang.xml"
  {
    echo "<dc:title>Cure Dolly Transcript$ref</dc:title>"
    echo "<dc:description>Hello, everyone. My name is Cure Dolly and I am here to teach you Organic Japanese. What is Organic Japanese? It is Japanese pure and simple, with no harmful additives. Japanese is the simplest, most logical, most easily understandable language I have ever encountered – much easier than Western languages.</dc:description>"
    echo "<dc:language>ja</dc:language>"
    echo "<dc:language>$lang</dc:language>"
    echo "<dc:creator>Cure Dolly</dc:creator>"
    echo "<dc:contributor>nunko</dc:contributor>"
    echo "<dc:contributor>Mordraug</dc:contributor>"
    echo "<dc:contributor>Kellenok</dc:contributor>"
    echo "<dc:contributor>coffeepebble</dc:contributor>"
    echo "<dc:publisher>Organic Japanese with Cure Dolly</dc:publisher>"
  } >"$metadata_file"
  find config/docs/"$lang" -name '*.md' | sort -V | xargs pandoc -f markdown+rebase_relative_paths+east_asian_line_breaks --toc --split-level=1 --epub-metadata="$metadata_file" --css=./config/stylesheet.css -o "cure-dolly-$lang.epub"
  rm -f "$metadata_file"
done
